/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	nsxerrorv1 "github.com/yktsubo/nsxerror/pkg/apis/nsxerror/v1"
	versioned "github.com/yktsubo/nsxerror/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yktsubo/nsxerror/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/yktsubo/nsxerror/pkg/client/listers/nsxerror/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NSXErrorInformer provides access to a shared informer and lister for
// NSXErrors.
type NSXErrorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.NSXErrorLister
}

type nSXErrorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNSXErrorInformer constructs a new informer for NSXError type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNSXErrorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNSXErrorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNSXErrorInformer constructs a new informer for NSXError type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNSXErrorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmwareV1().NSXErrors(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VmwareV1().NSXErrors(namespace).Watch(options)
			},
		},
		&nsxerrorv1.NSXError{},
		resyncPeriod,
		indexers,
	)
}

func (f *nSXErrorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNSXErrorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nSXErrorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nsxerrorv1.NSXError{}, f.defaultInformer)
}

func (f *nSXErrorInformer) Lister() v1.NSXErrorLister {
	return v1.NewNSXErrorLister(f.Informer().GetIndexer())
}
