/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/yktsubo/nsxerror/pkg/apis/nsxerror/v1"
	scheme "github.com/yktsubo/nsxerror/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NSXErrorsGetter has a method to return a NSXErrorInterface.
// A group's client should implement this interface.
type NSXErrorsGetter interface {
	NSXErrors(namespace string) NSXErrorInterface
}

// NSXErrorInterface has methods to work with NSXError resources.
type NSXErrorInterface interface {
	Create(*v1.NSXError) (*v1.NSXError, error)
	Update(*v1.NSXError) (*v1.NSXError, error)
	UpdateStatus(*v1.NSXError) (*v1.NSXError, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NSXError, error)
	List(opts metav1.ListOptions) (*v1.NSXErrorList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NSXError, err error)
	NSXErrorExpansion
}

// nSXErrors implements NSXErrorInterface
type nSXErrors struct {
	client rest.Interface
	ns     string
}

// newNSXErrors returns a NSXErrors
func newNSXErrors(c *VmwareV1Client, namespace string) *nSXErrors {
	return &nSXErrors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nSXError, and returns the corresponding nSXError object, and an error if there is any.
func (c *nSXErrors) Get(name string, options metav1.GetOptions) (result *v1.NSXError, err error) {
	result = &v1.NSXError{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nsxerrors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NSXErrors that match those selectors.
func (c *nSXErrors) List(opts metav1.ListOptions) (result *v1.NSXErrorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NSXErrorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nsxerrors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nSXErrors.
func (c *nSXErrors) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nsxerrors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a nSXError and creates it.  Returns the server's representation of the nSXError, and an error, if there is any.
func (c *nSXErrors) Create(nSXError *v1.NSXError) (result *v1.NSXError, err error) {
	result = &v1.NSXError{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nsxerrors").
		Body(nSXError).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nSXError and updates it. Returns the server's representation of the nSXError, and an error, if there is any.
func (c *nSXErrors) Update(nSXError *v1.NSXError) (result *v1.NSXError, err error) {
	result = &v1.NSXError{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nsxerrors").
		Name(nSXError.Name).
		Body(nSXError).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *nSXErrors) UpdateStatus(nSXError *v1.NSXError) (result *v1.NSXError, err error) {
	result = &v1.NSXError{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nsxerrors").
		Name(nSXError.Name).
		SubResource("status").
		Body(nSXError).
		Do().
		Into(result)
	return
}

// Delete takes name of the nSXError and deletes it. Returns an error if one occurs.
func (c *nSXErrors) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nsxerrors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nSXErrors) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nsxerrors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nSXError.
func (c *nSXErrors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NSXError, err error) {
	result = &v1.NSXError{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nsxerrors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
